services:
  docs:
    image: django_educational_demo_application_local_docs
    container_name: django_educational_demo_application_local_docs
    build:
      context: rm-django_educational_demo_application
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - .envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_educational_demo_application:/app/django_educational_demo_application:z
    ports:
      - '9000:9000'
    command: /start-docs
