services:
  docs:
    image: demo_for_diploma_local_docs
    container_name: demo_for_diploma_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./demo_for_diploma:/app/demo_for_diploma:z
    ports:
      - '9000:9000'
    command: /start-docs
